local uilib = require('lib.uilib')

local characterSheet = {
    uilib.Panel({
        position= "0 0 -0.01",
        rotation = "0 0 180",
        raycastTarget = false,
        color = "rgba(1, 1, 1, 0)",
        scale = "0.5 0.5",
        width = 3330,
        height = 4600
    }, {
        uilib.Panel({
            id = "characterSheet",
        },
        {
            uilib.InputField({
                id = "characterNameInput",
                navigation = "Explicit",
                selectOnDown = "classLevelInput",
                pivot = "0 0.5",
                position ="-1440 1980 0",
                width = 1000,
                height = 120,
                fontSize = 64,
                color = "rgba(0,0,0,0)",
                selectionColor = "#b5b5b555",
                characterLimit = 20,
                placeholder = "ИМЯ ПЕРСОНАЖА",
                font = "mookmania_bold",
            }),
            uilib.InputField({
                id = "classLevelInput",
                navigation = "Explicit",
                selectOnDown = "originInput",
                pivot = "0 0.5",
                position ="-210 2070 0",
                width = 550,
                height = 80,
                fontSize = 35,
                color = "rgba(0,0,0,0)",
                selectionColor = "#b5b5b555",
                characterLimit = 22,
                placeholder = "КЛАСС 1",
                font = "mookmania_regular",
            }),
            uilib.InputField({
                id = "originInput",
                navigation = "Explicit",
                selectOnDown = "playerNameInput",
                pivot = "0 0.5",
                position ="375 2070 0",
                width = 550,
                height = 80,
                fontSize = 35,
                color = "rgba(0,0,0,0)",
                selectionColor = "#b5b5b555",
                characterLimit = 22,
                placeholder = "ПРОИСХОЖДЕНИЕ",
                font = "mookmania_regular",
            }),
            uilib.InputField({
                id = "playerNameInput",
                navigation = "Explicit",
                selectOnDown = "raceInput",
                pivot = "0 0.5",
                position ="1070 2070 0",
                width = 400,
                height = 80,
                fontSize = 35,
                color = "rgba(0,0,0,0)",
                selectionColor = "#b5b5b555",
                characterLimit = 12,
                placeholder = "ИМЯ ИГРОКА",
                font = "mookmania_regular",
            }),
            uilib.InputField({
                id = "raceInput",
                navigation = "Explicit",
                selectOnDown = "alignmentInput",
                pivot = "0 0.5",
                position ="-210 1890 0",
                width = 550,
                height = 80,
                fontSize = 35,
                color = "rgba(0,0,0,0)",
                selectionColor = "#b5b5b555",
                characterLimit = 22,
                placeholder = "РАСА",
                font = "mookmania_regular",
            }),
            uilib.InputField({
                id = "alignmentInput",
                navigation = "Explicit",
                selectOnDown = "experienceInput",
                pivot = "0 0.5",
                position ="375 1890 0",
                width = 550,
                height = 80,
                fontSize = 35,
                color = "rgba(0,0,0,0)",
                selectionColor = "#b5b5b555",
                characterLimit = 20,
                placeholder = "МИРОВОЗРЕНИЕ",
                font = "mookmania_regular",
            }),
            uilib.InputField({
                id = "experienceInput",
                navigation = "Explicit",
                selectOnDown = "personaInput",
                pivot = "0 0.5",
                position ="1070 1890 0",
                width = 400,
                height = 80,
                fontSize = 35,
                color = "rgba(0,0,0,0)",
                selectionColor = "#b5b5b555",
                characterLimit = 12,
                placeholder = "ОПЫТ",
                font = "mookmania_regular",
            }),
            uilib.InputField({
                id = "personaInput",
                navigation = "Explicit",
                selectOnDown = "idealsInput",
                lineType = "MultiLineNewLine",
                pivot = "0 1",
                position ="640 1580 0",
                width = 860,
                height = 300,
                fontSize = 40,
                color = "rgba(0,0,0,0)",
                selectionColor = "#b5b5b555",
                characterLimit = 180,
                placeholder = ". . .",
                font = "mookmania_regular",
            }),
            uilib.InputField({
                id = "idealsInput",
                navigation = "Explicit",
                selectOnDown = "bondsInput",
                lineType = "MultiLineNewLine",
                pivot = "0 1",
                position ="640 1160 0",
                width = 860,
                height = 220,
                fontSize = 40,
                color = "rgba(0,0,0,0)",
                selectionColor = "#b5b5b555",
                characterLimit = 120,
                placeholder = ". . .",
                font = "mookmania_regular",
            }),
            uilib.InputField({
                id = "bondsInput",
                navigation = "Explicit",
                selectOnDown = "flawsInput",
                lineType = "MultiLineNewLine",
                pivot = "0 1",
                position ="640 820 0",
                width = 860,
                height = 220,
                fontSize = 40,
                color = "rgba(0,0,0,0)",
                selectionColor = "#b5b5b555",
                characterLimit = 120,
                placeholder = ". . .",
                font = "mookmania_regular",
            }),
            uilib.InputField({
                id = "flawsInput",
                navigation = "Explicit",
                selectOnDown = "featuresInput",
                lineType = "MultiLineNewLine",
                pivot = "0 1",
                position ="640 480 0",
                width = 860,
                height = 220,
                fontSize = 40,
                color = "rgba(0,0,0,0)",
                selectionColor = "#b5b5b555",
                characterLimit = 120,
                placeholder = ". . .",
                font = "mookmania_regular",
            }),
            uilib.InputField({
                id = "featuresInput",
                navigation = "Explicit",
                selectOnDown = "attacksSpellsInput",
                lineType = "MultiLineNewLine",
                pivot = "0 1",
                position ="590 100 0",
                width = 960,
                height = 2250,
                fontSize = 32,
                color = "rgba(0,0,0,0)",
                selectionColor = "#b5b5b555",
                placeholder = ". . .",
                font = "mookmania_regular",
            }),
            uilib.InputField({
                id = "attacksSpellsInput",
                navigation = "Explicit",
                selectOnDown = "inventoryInput",
                lineType = "MultiLineNewLine",
                pivot = "0 1",
                position ="-480 -320 0",
                width = 960,
                height = 680,
                fontSize = 32,
                characterLimit = 800,
                color = "rgba(0,0,0,0)",
                selectionColor = "#b5b5b555",
                placeholder = ". . .",
                font = "mookmania_regular",
            }),
            uilib.InputField({
                id = "inventoryInput",
                navigation = "Explicit",
                selectOnDown = "proficiencyInput",
                lineType = "MultiLineNewLine",
                pivot = "0 1",
                position ="-210 -1180 0",
                width = 670,
                height = 960,
                fontSize = 40,
                characterLimit = 400,
                color = "rgba(0,0,0,0)",
                selectionColor = "#b5b5b555",
                placeholder = ". . .",
                font = "mookmania_regular",
            }),
            uilib.InputField({
                id = "proficiencyInput",
                navigation = "Explicit",
                lineType = "MultiLineNewLine",
                pivot = "0 1",
                position ="-1540 -1370 0",
                width = 950,
                height = 800,
                fontSize = 40,
                characterLimit = 400,
                color = "rgba(0,0,0,0)",
                selectionColor = "#b5b5b555",
                placeholder = ". . .",
                font = "mookmania_regular",
            }),
        })
    }
)
}

--[[
    uilib.loop(times, attributesToAdd, uiToReplicate) -> array of replicated ui elements
]]



return characterSheet